version: '3'

services:
  db:
    image: postgres
    env_file:
      - .env

  web:
    build: .
    command: ./entrypoint.sh
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
